---

- hosts: masterNodes,dataNodes,queryNode
  gather_facts: yes
  vars_files:
    - vars/druid.yml
  roles:
    - java

#- hosts: zookeepers
#  vars_files:
#    - vars/druid.yml
#  roles:
#    - zookeeper

- hosts: masterNodes
  vars_files:
    - vars/druid.yml
  roles:
    - setup

- hosts: dataNodes
  vars_files:
    - vars/druid.yml
  roles:
    - setup

- hosts: queryNode
  vars_files:
    - vars/druid.yml
  roles:
    - setup
